### ISSUE TITLE
Unexpected Token with 1.0.5

### ISSUE THREAD

**Issue by Neilski** [softsimon/angular-2-dropdown-multiselect#104]
I am trying to use the angular-2-dropdown-multiselect@1.0.5 with Angular-2 (2.4.9) TypeScript (2.2.1) and Webpack (2.2).  When I try and build the application I get the following error:

```
ERROR in ../~/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts
Module parse failed: \node_modules\angular-2-dropdown-multiselect\src\multiselect-dropdown.ts Unexpected token (26:32)
```

Here is my _tsconfig.json_ file for reference:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es7", "dom" ],
    "noImplicitAny": false,
    "noEmitOnError": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "../tsBuild",
    "typeRoots": [
      "../node_modules/@types/"
    ]
  }
}
```

I am very new to both TypeScript and Webpack, so please excuse me if this is a 'user error'!

**Comment by blopez-co-slo-ca-us** [comment]
Did you ever find a resolution to this issue? I'm having the same problem but with AOT.  In my case I can build the app (at least I think). The problem surfaces on rollup.

**Comment by chris--jones** [comment]
I don't know what your issue is, but here's my working folder (latest angular & webpack) for my [demo page:
](https://chris--jones.github.io/angular-2-dropdown-multiselect/)https://github.com/chris--jones/angular-2-dropdown-multiselect/tree/gh-pages

**Comment by Neilski** [comment]
Thanks Chris, this was very helpful. In my ignorance, I had the following section in my webpack.config.js file:

```
{
    // TypeScript
    test: /\.ts$/,

    use: [
        {
            loader: 'awesome-typescript-loader',
            exclude: /(node_modules)/,
            options: { configFileName: settings.srcFolder('./tsconfig.json') }
        }, 'angular2-template-loader'
    ]
}
```
The _exclude_ statement was causing the problem.  I was also **importing** _MultiselectDropdownModule_ into **@NgModule**, but I noticed you declare it in the **declarations** section.

All working now - thanks for your help.

**Comment by falconlaravguru** [comment]
Hi, Neilski.
I have problem with this package, not as yours.
When I was integrating Angular 2 into Laravel 5.4, i reached the error like below.

` ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./~/raw-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./~/angular2-multisele
ct-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.scss
Module build failed:
.cuppa-dropdown{
             ^
      Invalid CSS after "module.exports": expected "{", was '= ".cuppa-dropdown '
      in F:\mine\Angular2\LaravelFFT\node_modules\angular2-multiselect-dropdown\src\app\angular2-multiselect-dropdown\multiselect.component.scss (line 1, colum
n 15)
 @ ./~/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.scss 4:14-267
 @ ./~/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts
 @ ./~/angular2-multiselect-dropdown/angular2-multiselect-dropdown.ts
 @ ./resources/assets/typescript/app/app.module.ts
 @ ./resources/assets/typescript/boot.ts

ERROR in ./~/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.scss
Module build failed: ModuleBuildError: Module build failed:
.cuppa-dropdown{
             ^
      Invalid CSS after "module.exports": expected "{", was '= ".cuppa-dropdown '
      in F:\mine\Angular2\LaravelFFT\node_modules\angular2-multiselect-dropdown\src\app\angular2-multiselect-dropdown\multiselect.component.scss (line 1, colum
n 15)
    at F:\mine\Angular2\LaravelFFT\node_modules\webpack\lib\NormalModule.js:141:35
    at F:\mine\Angular2\LaravelFFT\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\mine\Angular2\LaravelFFT\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (F:\mine\Angular2\LaravelFFT\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (F:\mine\Angular2\LaravelFFT\node_modules\sass-loader\lib\loader.js:55:13)
    at Object.<anonymous> (F:\mine\Angular2\LaravelFFT\node_modules\async\dist\async.js:2244:31)
    at Object.callback (F:\mine\Angular2\LaravelFFT\node_modules\async\dist\async.js:906:16)
    at options.error (F:\mine\Angular2\LaravelFFT\node_modules\node-sass\lib\index.js:294:32)`
   
And in my webpack.config.js
I wrote some code like this

config.module = {
    rules: [
      // Support for .ts files.
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader', '@angularclass/hmr-loader'],
        exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
      },

      // copy those assets to output
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader?name=fonts/[name].[hash].[ext]?'
      },

      // Support for *.json files.
      {test: /\.json$/, loader: 'json-loader'},

      // Support for CSS as raw text
      // use 'null' loader in test mode (https://github.com/webpack/null-loader)
      // all css in src/style will be bundled in an external css file
      {
        test: /\.css$/,
        exclude: root('resources/assets/typescript', 'app'),
        loader: isTest ? 'null-loader' : ExtractTextPlugin.extract({ fallback: 'style-loader', use: ['css-loader', 'postcss-loader']})
      },
      // all css required in src/app files will be merged in js files
      {test: /\.css$/, include: root('resources/assets/typescript', 'app'), loader: 'raw-loader!postcss-loader'},

      // support for .scss files
      // use 'null' loader in test mode (https://github.com/webpack/null-loader)
      // all css in src/style will be bundled in an external css file
      {
        test: /\.(scss|sass)$/,
        exclude: root('resources/assets/typescript', 'app'),
        loader: isTest ? 'null-loader' : ExtractTextPlugin.extract({ fallback: 'style-loader', use: ['css-loader', 'postcss-loader', 'sass-loader']})
      },
      // all css required in src/app files will be merged in js files
      {test: /\.(scss|sass)$/, exclude: root('resources/assets/typescript', 'style'), loader: 'raw-loader!postcss-loader!sass-loader'},

      // support for .html as raw text
      // todo: change the loader to something that adds a hash to images
      {test: /\.html$/, loader: 'raw-loader',  exclude: root('resources/assets/typescript', 'public')}
    ]
  };

Someone told me that it's up to sass-loader, but I don't think so.
Because I've already webpack with .scss file in my angular directory, so that It seems like that this issue is about exclude configuration or loader. But my idea wasn't correct. And Now, I don't know what reason is correctly.
I hope that you'll solve this error and plz let me know.

Thanks.
Falcon

**Comment by Neilski** [comment]
Hi Falcon,  I have no experience with the Laravel environment.  All I can suggest is that you try and reduce your project down to just the `angular-2-dropdown-multiselect` reference and then try building it from there.  If it still fails, pay particular attention to the component issues being used (TypeScript version in particular).  Sorry I can't be more help.
