### ISSUE TITLE
Support for using a list of any model object rather than IMultiSelectOption

### ISSUE THREAD

**Issue by pgeyman** [softsimon/angular-2-dropdown-multiselect#109]
Hi,

It is quite frustrating to have to create a separate array of values specifically for the list every time I need to display any model data in a multi-select dropdown.

Please add support for being able to use a list of any data object rather than forcing the use of IMultiSelectOption. You could specify the id and name mapping in your IMultiSelectSettings.

eg. idProperty?:string, nameProperty?:string

maybe with a flag to say use custom model:

useCustomModel?: boolean

**Comment by chris--jones** [comment]
I don't see why this is a big deal, a mapping function in typescript is as simple as
```typescript
model.map(m => ({ id: m.idProperty, name: m.nameProperty }))
```

Whereas the development effort to support arbitrary models would be non-trivial and remove the type safety afforded by the current approach. I also think a truly open and un-opinionated solution would require the option of a function to determine the id and name properties (potentially others).

**Comment by hewstone** [comment]
It would make it easier to be able to bind directly a list of my own objects.  It's true it's easy to just call a map function to create a list of items to bind to.  The issue becomes when I want to bind the selected items to a specific type of list items.  I can't directly bind to the selected items because they are IMultiSelectOption.  I have to do a map call then directly set the items.

accepting an any type of list items would be ideal.  Couple that with a setting that would define the id and the name (or method to return the format of the display string).

**Comment by chris--jones** [comment]
I've done some work on this, however it's currently only supporting id and name properties (so you lose label and parent functionality): https://github.com/chris--jones/angular-2-dropdown-multiselect/tree/feature/allow_options_of_type_any

I'm still not convinced this is a sustainable solution. As I've also mentioned it's not possible to support any arbitrary option model unless we allow you to assign your own map function which is the same effort as simply mapping before initialisation.

**Comment by nicholasguyett** [comment]
Yeah, any attempt to support arbitrary models will require you to implement a mapping in some manner, regardless.  Just as you would have to with any other input type with a different model than you.

As for binding, you can bind the model to a getter and setter, which can map to and from the format you want.

**Comment by chris--jones** [comment]
I think we can revisit this alongside better lazy data source loading if and when we do another major version.
