### ISSUE TITLE
Is there a way to select dynamically?(sorry about reregister..;;)

### ISSUE THREAD

**Issue by pangky24** [softsimon/angular-2-dropdown-multiselect#120]
sorry about reregister..

@nicholasguyett
sorry already I have studied ngModel, but I don't understand about your answer below..

you just mean..
if I want to make selected status, just set the formConrolName's value?

please, explain how I try..

html
<ss-multiselect-dropdown [options]="countryListOptions" formControlName="fltTrgtUsrCtr_"
[settings]="pushSettings"></ss-multiselect-dropdown>

ts
**this.form.controls["fltTrgtUsrCtr_"] = .... (array value?)**

https://github.com/softsimon/angular-2-dropdown-multiselect/issues/118

![image](https://cloud.githubusercontent.com/assets/3896324/24691530/e7e0d866-1a0e-11e7-865c-27d8e93ad0b6.png)

**Comment by nicholasguyett** [comment]
My answer was specific to ngModel, since that's the usual use.  However, its similar for form controls.  I haven't used them before, so I don't have a code example.  But look up how to set the form controls from the component, and set the value as an array that contains the value you want selected.  E.g., if you want to select the value and and no other values, you should set the value as `currentValue.concat(valueToSelect)` after confirming that the value you want is not already in the current value.

**Comment by pangky24** [comment]
thanks @nicholasguyett 

I have solved this problem that was wrong when I set values to formcontrols below.

I've got to use formcontrols's '.setValue()' method when I set.
and then the selected value appears..

before.
var optionArr = this.item[key].split(",");
this.form.controls[key+"_"] = optionArr;

after.
var optionArr = this.item[key].split(",");
this.form.controls[key+"_"].setValue(optionArr);
