### ISSUE TITLE
Reactive form returns errors

### ISSUE THREAD

**Issue by natcohen** [softsimon/angular-2-dropdown-multiselect#209]
I have followed the tutorial for reactive model and have this:

        this.myOptions = [
            { id: 1, name: 'English' },
            { id: 2, name: 'French' },
        ];

        this.form = this.formBuilder.group({
            langs:[1, 2]
        });

And in my html (in pug):

        ss-multiselect-dropdown([options]='myOptions', formControlName='langs')

And get the following error: `TypeError: this.validator is not a function`

So I've tried:

        this.form = this.formBuilder.group({
            langs:this.formBuilder.array([1, 2])
        });

And get the following error `TypeError: control.registerOnChange is not a function`.

What am I doing wrong? Is this a bug?

You can see a [plunker here](https://plnkr.co/edit/MzukQC8M7l0xUKBC0wL5?p=preview)

**Comment by h6784rfg6** [comment]
The correct solution is:

```
this.form = this.formBuilder.group({
    langs:[[1, 2]]
});
```

Why?
Because the szntax of the `formControlName` is as follows: `['Initial value, which in this case is an array', validator function]`.

If you just pass `[1, 2]` it takes `1` as initial value and the `2` as the validator -> 2 is not a function. An example validator would be `Validators.required`.
