### ISSUE TITLE
Overriding dropdown min-width

### ISSUE THREAD

**Issue by jamesbcn** [softsimon/angular-2-dropdown-multiselect#219]
Is is possible to override the min-width of the dropdown menu?

I didn't see an option in the customize section.

**Comment by nicholasguyett** [comment]
https://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency

**Comment by nicholasguyett** [comment]
There's no option in the api, but it should be relatively easy to override via CSS.  Give that a try and let me know if that meets your requirements.

**Comment by Quayle57** [comment]
Hello,
I can't find the way to use CSS to customize the with
I tried to select with `.dropdown-menu`, `body dropdown-menu`, `ss-multiselect-dropdown .dropdown-menu` , ...with width in %, with and without `!important` but it doesn't work.
Maybe it's because the dropdown ul doesn't exists in the DOM while it's not clicked on but is there any way to style it without modifying the source code ?

**Comment by nicholasguyett** [comment]
CSS is the way to style it without modifying the source code.   If you can't find the element to override, I'll take a look at this later this week and show you which selector to override.

**Comment by Ezeon** [comment]
The following works for me:

:host /deep/ ss-multiselect-dropdown .dropdown {
	width: 150px;
	display: block;
}

:host /deep/ ss-multiselect-dropdown .dropdown-toggle {
	width: 100%;
	text-align: left;
}

:host /deep/ ss-multiselect-dropdown .caret {
	float: right;
	margin-top: 8px;
}

**Comment by Quayle57** [comment]
Thank you ! I didn't know about the shadow DOM yet and it works like a charm !

**Comment by jamesbcn** [comment]
Thanks everyone. Works great.
