### ISSUE TITLE
Cannot change size of dropdown

### ISSUE THREAD

**Issue by subhani1249** [softsimon/angular-2-dropdown-multiselect#38]
![mulitselect](https://cloud.githubusercontent.com/assets/10893928/21072846/693c3146-bef5-11e6-90ce-8dea02202e60.PNG)

**Comment by nicholasguyett** [comment]
Just to verify, the issue you're experiencing is that the dropdown does not extend to fill the whole region?  If so, that is expected behavior.

The col-lg-3 class is only applying to the parent, not the dropdown itself.  This is consistent with the behavior of the native select[multiple] element.

However, I did not that the appropriate solution (applying the width styling or a form-control class to the dropdown element itself) does not result in the correct results either.  I'll make an update later which allows you to style the width of the drodown.

**Comment by smorcuend** [comment]
Hi!

A posible solution to it's works, as @subhani1249 says, would be change this:
```
<div class="btn-group">
            <button type="button" class="dropdown-toggle" ....></button>
```
 to this:  
```
<div class="dropdown">
            <button type="button" class="dropdown-toggle" ....></button>
```
I only have checked it out with bootstrap v4 and works ok.

It's more semantically correct to use '.dropdown' class attribute. '.btn-group' is not necessary here because you are not grouping buttons.

**Comment by softsimon** [comment]
Class has been changed to <div class="dropdown"> in latest version.

**Comment by ermarkar** [comment]
still not able to change width?

**Comment by chris93007** [comment]
Same issue!
