### ISSUE TITLE
Getting 404 Error 

### ISSUE THREAD

**Issue by sunpasup** [softsimon/angular-2-dropdown-multiselect#41]
after following the Usage given in GiT i am Getting 404 Error like below not sure what i missed.

<img width="1440" alt="screen shot 2016-12-15 at 3 15 38 pm" src="https://cloud.githubusercontent.com/assets/24596204/21245791/7bc3fb2c-c2d9-11e6-8bdf-c81c1cf9f24b.png">

**Comment by nicholasguyett** [comment]
I believe your issue is most likely the result of #19.  The compiled JS is not currently include in the NPM package and so your project is unable to locate the file.

The current workaround is to [tsc](https://www.npmjs.com/package/typescript) from within the package directory, which will generate the necessary files.  This should be resolved in the next package version, though.
