### ISSUE TITLE
Populate myOptions from a json

### ISSUE THREAD

**Issue by bryan-mwas** [softsimon/angular-2-dropdown-multiselect#52]
Hi,
How do I populate the options from a JSON file?

Thanks.

**Comment by dessalines** [comment]
I'd highly suggest against using a `.json` file to store this, since they aren't bundled with the rest of the ts files, and must be "fetched" with an observable. You could then fill the options object with the subscribe results, and make sure you instantiate the component **after** the subscribe returns a result.

If you want to define it, I suggest using a `.ts` file instead.

**Comment by nicholasguyett** [comment]
As @dessalines said, the correct would be to request it and simply pass the data to the options array like normal.  The component will correctly update if you pass a new array.  If you are fetching it with an observable, you can simply pipe it using async like this

```
<ss-multiselect-dropdown [options]="monthlyCharges$ | async" name="monthlyChargeIds" [(ngModel)]="monthlyChargeIds"></ss-multiselect-dropdown>
```

This is an actual example from my own code.
