### ISSUE TITLE
Does not work with non-systemjs transpilers

### ISSUE THREAD

**Issue by ashokac** [softsimon/angular-2-dropdown-multiselect#60]
I see "Uncaught ReferenceError: System is not defined"

I am using "bootstrap 4.0.0-alpha.5" for my project. Please suggest if that worked for you.

**Comment by iacii** [comment]
I'm getting this error too, though I'm not using Bootstrap 4. In node_modules/angular-2-dropdown-multiselect/src, I noticed the following files:
- multiselect-dropdown.html
- multiselect-dropdown.ts
- multiselect-dropdown.js
- multiselect-dropdown.js.map

I don't think the .js files should be there. I'm little confused about how they're getting downloaded there, because I don't see them in the GitHub repo. Deleting those two files fixes the problem for me, but that's a less than ideal solution.

**Comment by softsimon** [comment]
The .js .js.map are there because they are published on NPM to fix #19, but that might have been a bad decision? I am using angular-cli and I am not getting this error as of now.

**Comment by iacii** [comment]
I'm no expert on these things, but I've noticed in many other libraries they have an index.js at the root along with a typescript definition file (index.d.ts). Then those files would reference files in a dist folder. For example: [https://github.com/gevgeny/angular2-highcharts](https://github.com/gevgeny/angular2-highcharts). Maybe something like that would work?

With that said, I did find another way to get it to work without deleting the js files. I simply changed my webpack config file to prioritize ts files first:

```javascript
resolve: { extensions: ['', '.ts', '.js'] }
```

instead of:

```javascript
resolve: { extensions: ['', '.js', '.ts'] }
```

**Comment by ashokac** [comment]
@iacii , Thanks for your response, But it didn't help me. I get the following error when I change the order in webpack.config.js. 

ERROR in ./~/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts
Module build failed: Error: Typescript emitted no output for /Users/chaas003/PTT/src/main/webapp/node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts
    at Object.loader (/Users/chaas003/PTT/src/main/webapp/node_modules/ts-loader/index.js:456:15)
 @ ./src/module/app.module.ts 19:29-95

**Comment by iacii** [comment]
This may explain why you're getting that error if you're using ts-loader to transpile your typescript: [https://github.com/TypeStrong/ts-loader/issues/278](https://github.com/TypeStrong/ts-loader/issues/278).

I'm using awesome-typescript-loader with no problems, so you may want to consider switching to that.

**Comment by Pavelyev** [comment]
I have the same issue `"Uncaught ReferenceError: System is not defined"` while using webpack

If place '.ts' before '.js' in webpack.config, then I got `Uncaught ZoneAwareError {__zone_symbol__error: Error: Unexpected value 'MultiselectDropdownModule'...`

**Comment by Pavelyev** [comment]
Version `0.4.0` works properly with 'angular2-template-loader' and having `resolve.extensions` `.ts` before `.js`. Thank you guys. I think that shipping package with .ts file is right way.

**Comment by nicholasguyett** [comment]
I've updated the exported module to use commonjs instead of systemjs.  If you're using webpack, this should resolve your issue.  Please try the latest release and let us know if this resolves your problem.

**Comment by nicholasguyett** [comment]
No response in 7 days.  Assuming the fix worked and closing issue.

**Comment by saggy2012** [comment]
HI, I am getting below error.
Error loading angular-2-dropdown-multiselect/src/multiselect-dropdown
can somebody plz help on this.
using systemjs.config.js file .
