### ISSUE TITLE
Multiselect dropdown does not get closed when placed inside modal popup and clicked outside 

### ISSUE THREAD

**Issue by vinidumbre** [softsimon/angular-2-dropdown-multiselect#70]
Hi,
I have implemented multiselect inside ng2-modal popup. 
But dropdown does not get closed when clicked outside it.
Please help.
Thanks.

**Comment by chris--jones** [comment]
I was only able to reproduce this when clicking to the right of the control.
This is because the wrapper/container div is a block element and fills the horizontal space (see my comment in #82) so it's not considered "clicking outside the control because the click is actually still landing in the component".

The proposed fix is to make the container inline-block by default.
