### ISSUE TITLE
ss-multiselect-dropdown does not work/load dropdown menu under table-tr tag

### ISSUE THREAD

**Issue by davesunny1985** [softsimon/angular-2-dropdown-multiselect#78]
ss-multiselect-dropdown does not work/load dropdown menu under table-tr tag

**Comment by nicholasguyett** [comment]
What exactly is not working?

The dropdown doesn't have any special handling for what container its in.

If you have any styles with "overflow: hidden" on one of its parent elements, that can hide the dropdown.  There's nothing that can be done from this end to fix that, so if that's the case, you'll need to adjust your css so that the dropdown is not cutoff.
